[package]
name = "alsd-helper"
version = "0.1.0"
authors = ["goose121 <goose121@users.noreply.github.com>"]
edition = "2018"

[dependencies]
netlink-rust = "0.1.0"
once_cell = "0.1.8"
error-chain = "0.12.0"
mio = "0.6.16"
tokio = "0.1.17"
tokio-reactor = "0.1.9"
futures = "0.1.25"
nix = "0.13.0"